### PR TITLE
Update to awk

### PR DESCRIPTION
**Pull request by hpincket**
Not sure if this will work, or even syntax check. But I think this is the gist of what you need.

### CODE REVIEW

**Comment by linuxcaffe** [comment]
tried it, borked everything, moved awk to external file and inserted dummy-text "Description"

Once we can determine that the awk part is returning the desire result, I'll figure out how to call it from the script (which is otherwise working well)

**Comment by hpincket** [comment]
I just ran the awk file against a simple test file. Seemed to work fine. (It keeps the space a the beginning of the definition, just so you know).

When it 'Borked', did you get wrong values? or does it just not run?

**Comment by linuxcaffe** [comment]
well at the time, as it was (all in one file) everything screwed up with the tags part. anyhow, past that! Now gen-index runs as expected without the awk part.

Now I suspect my next problem is the invocation in gen-index line # 22 (to replace line # 21)

**Comment by linuxcaffe** [comment]
I think maybe I'm not feeding awk correctly.. how did you run the small test?? 

does awk need to be surrounded with " ' " ?

does line # 22 look ok?

**Comment by hpincket** [comment]
It looks similar to what I did, though I passed the file as an argument:

`awk -f def-desc.awk test.wiki`

**Pull request merged**
